---
- name: Test S3 with Virtual Environment
  hosts: localhost
  gather_facts: true
  
  tasks:
    - name: Display Python environment
      debug:
        msg: "Using Python: {{ ansible_python_interpreter | default('default') }}"
    
    - name: Create S3 bucket
      amazon.aws.s3_bucket:
        name: "timeout-poc2-bucket-{{ ansible_date_time.epoch }}"
        state: present
        region: ap-south-1
        
    - name: Success message
      debug:
        msg: "S3 bucket created successfully using virtual environment!"
